### ISSUE TITLE
HfLA: Summer 2025 Potluck: Create Meetup Invite

### ISSUE THREAD

**Issue by Rabia2219** [civictechstructure/party#27]
### Dependencies
- [x] #26 

### Overview
We need to create the meetup invite for this year's summer potluck so that we can publish the event

### Action Items

- [x] Copy and paste the template below (Resource 1.0) into a new comment
- [x] customize only the following in the template
  - [x] add the finalized date and time
  - [x] the year in `See details...`
- [x] copy the contents of the comment
- [x] save the comment
- [x] add it under resource 4.0 of #33

#### Template to fill out:
````
   - Title (required): Hack for LA Member Summer Potluck Picnic!
   - Date and time: 
   - Duration: 3 hours
   - Featured Photo: follow steps above
   - Description (required):
   ```
   Join us for a fun-filled summer potluck picnic in the park if you are in Los Angeles and are a member of Hack for LA*.

   💝 Bring partners & friends, or come on your own.

   Step 1 - RSVP
   ✅ RSVP now to this meetup.

   Step 2 - See Potluck Details
   See all the details in our members only, Hack for LA [#summer-potluck-YYYY-la](link to channel) Slack channel.

   🗝️ If you are not yet a member of Hack for LA, we will see you at next year's party after you have joined one of our upcoming       onboarding sessions https://meetup.com/hackforla/events and volunteered!

   *We define members as someone who has completed onboarding and has volunteered at Hack for LA.

   ```

   - Location:
      - In person
      - Add venue: 
        - Name: Secret Location
        - Country: USA
        - Address: 123
        - City: Los Angeles
        - State: California
       - How to find us
         - See details in our [#summer-potluck-2025-la] Slack channel
```
